In [ ]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.1.0'

In [5]:
x = tf.constant(2)
y = tf.constant(4)

In [6]:
z = x + y

In [7]:
z1 = tf.add(x,y)

In [11]:
print(tf.math.add(x,y,name=None))

tf.Tensor(6, shape=(), dtype=int32)


In [15]:
print(tf.math.add(x,y,name=None))

tf.Tensor(6, shape=(), dtype=int32)


In [22]:
tf.zeros([5,5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [23]:
x1 = np.array([[3,2,5,7],[6,7,8,2]])
x2 = np.array([[4,6,8,1],[12,4,7,2]])

In [26]:
# print(tf.math.add(x1,x2))
tf.math.add(x1,x2)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 7,  8, 13,  8],
       [18, 11, 15,  4]])>

In [27]:
x1 = tf.Variable(10)
x2 = tf.Variable(12)

In [29]:
z2 = x1 + x2

In [30]:
print(z2)

tf.Tensor(22, shape=(), dtype=int32)


In [32]:
# tf.compat.v1.placeholder

In [42]:
# decorator
@tf.function
def multiply(x,y):
    z = tf.matmul(x,y)
    return z

x = np.random.randint(1,20,[3,3])
y = np.random.randint(1,20,[3,3])
multiply(x,y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[191, 117, 285],
       [264, 256, 513],
       [223, 106, 272]])>